# [meta]
# Name of the simulation. May be ommitted.
# name = "PRWG lipopeptide micelle in water"
# Tags classifying the simulation. May be ommitted.
# tags = ["lipopeptides", "PRWG"]

# Here's the topology of a PRWG molecule
#
#                   WSC2 -- WSC3
#                   |       |
#    PSC(+)        WSC1 -- WSC4
#    |             |
#    PBB -- RBB -- WBB -- GBB -- C -- C -- C -- C 
#           |
#           RSC -- RSC(+)
#

[particles]
# Number of total particles in the simulation. If an input .hdf5 format file is
# specified, the number of particles will be inferred from this and *may* be
# ommited here.
n_particles = 11876
# specify number of ghost particles, used for dipole point charges in the CBT dihedral potential (default = 0)
# n_ghots = 0
# Mass of the particles in [g/mol]. All masses are assumed equal.
mass = 72.0
# Maximum number of particles per molecules present in the system. A default of
# 200 is assumed, and this keyword may be ommitted for any system with smaller
# molecules.
# max_molecule_size = 15

[simulation]
# Number of total time steps in the simulation.
n_steps = 200
# Frequency of trajectory/energy file output in time steps.
n_print = 1
# Frequency of requesting that the HDF5 library flush the file output buffers
# to disk after in number of n_print timesteps.
n_flush = 10
# Time step used in the simulation in [picoseconds].
time_step = 0.03
# Simulation box size in [nanometers].
box_size = [10.73911, 10.76184, 11.30546]
# box_size = [5.0, 5.0, 5.0] # for single PRWG molecule test
# Time integrator used in the simulation. Either "velocity-verlet" or "respa".
# If "respa", specify also the number of small rRESPA time steps per large
# time_step with the 'respa_inner' keyword.
integrator = "respa"
respa_inner = 5
# Perform MPI rank domain decomposition every x time steps to (hopefully)
# reduce the amount of neccessary communication between ranks in the pmesh
# procedures. Ommit or set to 'false' or '0' to not perform any domain
# decomposition.
domain_decomposition = 1000
# domain_decomposition = false
# Remove linear center of mass momentum from the system before integration
# starts.
cancel_com_momentum = true
# Starting temperature to generate before simulation begins in [kelvin]. Ommit
# or set to 'false' to not change the temperature before starting.
start_temperature = 300
# Target temperature used in the velocity rescale thermostat in [kelvin]. Ommit
# or set to 'false' to use no thermostat, i.e. a constant energy simulation.
target_temperature = 300
# Thermostat collision frequency in [1/picoseconds].
tau = 1
# Couple groups of particles species to individual different thermostats.
thermostat_coupling_groups = [
  ["PBB", "PSC", "RBB", "RSC", "WBB", "WSC1", "WSC2", "WSC3", "WSC4", "GBB", "C"], 
  ["W", "CL"]
]
# The energy functional W[phi] to use. Options:
#    "SquaredPhi":      φ² / 2κφ₀,
#    "DefaultNoChi":   (φ - φ₀)² / 2κφ₀
#    "DefaultWithChi": (φ - φ₀)² / 2κφ₀ + Σ χφφ' / φ₀
# Subclass Hamiltonian to create a new energy functional.
hamiltonian = 'DefaultWithChi'
coulombtype = 'PIC_Spectral'
dielectric_const = 80.0

[field]
# Particle-mesh grid size, either a single integer or an array of 3 integers
# (number of grid points in each dimension). In order to guarantee consistency
# and speed in the PFFT routines, the actual mesh grid will be changed to ensure
# that each dimension of the 2d PFFT process grid divides each dimension of the
# mesh grid size.
mesh_size = [24, 24, 24]
# Compressibility used in the relaxed incompressibility term of W(phi) in
# [mol/kJ].
kappa = 0.05
# Standard deviation in the Gaussian filter (window function) in [nanometers].
# This value is a characteristic length scale for the size of the particles in
# the simulation.
sigma = 0.5
# Interaction matrix, chi, ((atom name 1, atom name 2), (mixing energy in
# [kJ/mol])).
chi = []