[meta]
name = "Biphasic system"
tags = ["biphase", "AB", "monoatomic"]

[particles]
n_particles = 10555
mass = 18.0
max_molecule_size = 1 

[simulation]
n_steps = 2 
n_print = 1
n_flush = 1000
time_step = 0.03
box_size = [10.6, 10.6, 10.6]
integrator = "respa"
respa_inner = 10
domain_decomposition = 25
start_temperature = 300
target_temperature = 300
tau = 0.7
hamiltonian = 'DefaultWithChi'
pressure = true
plot = false

[field]
mesh_size = [24, 24, 24]
kappa = 0.05
sigma = 0.238
rho_0 = 8.86
a = 10.67
chi = [
  [["A", "B"], [36]],
]
