[system]
name = "DPPC in water"
# molname      N_mols
molecules = [
  ["DPPC", 100],
  ["W", 1000],
]

[DPPC]
atomnum = 12
atoms = [
# id 	type 	resnr 	residu 	atom 	cgnr 	charge
  [ 1, 	"Q0",	 1,	"DPPC",	"NC3",	 1,	1.0 ],
  [ 2, 	"Qa",	 1,	"DPPC",	"PO4",	 2,	-1.0],
  [ 3, 	"Na",	 1,	"DPPC",	"GL1",	 3,	0 	],
  [ 4, 	"Na",	 1,	"DPPC",	"GL2",	 4,	0 	],
  [ 5, 	"C1",	 1,	"DPPC",	"C1A",	 5,	0 	],
  [ 6, 	"C1",	 1,	"DPPC",	"C2A",	 6,	0 	],
  [ 7, 	"C1",	 1,	"DPPC",	"C3A",	 7,	0 	],
  [ 8, 	"C1",	 1,	"DPPC",	"C4A",	 8,	0 	],
  [ 9, 	"C1",	 1,	"DPPC",	"C1B",	 9,	0 	],
  [10, 	"C1",	 1,	"DPPC",	"C2B",	10,	0 	],
  [11, 	"C1",	 1,	"DPPC",	"C3B",	11,	0 	],
  [12, 	"C1",	 1,	"DPPC",	"C4B",	12,	0 	],
]

bonds = [
#  i  j 	funct 	length 	force.c.
  [ 1,   2,	1,	0.47,	1250],
  [ 2,   3,	1,	0.47,	1250],
  [ 3,   4,	1,	0.37,	1250],
  [ 3,   5,	1,	0.47,	1250],
  [ 5,   6,	1,	0.47,	1250],
  [ 6,   7,	1,	0.47,	1250],
  [ 7,   8,	1,	0.47,	1250],
  [ 4,   9,	1,	0.47,	1250],
  [ 9,  10,	1,	0.47,	1250],
  [10,  11,	1,	0.47,	1250],
  [11,  12,	1,	0.47,	1250],
]

angles = [
#  i  j  k 	funct 	angle 	force.c.
  [ 2,   3,  4,	2,	120.0,	25.0], 	
  [ 2,   3,  5,	2,	180.0,	25.0], 	
  [ 3,   5,  6,	2,	180.0,	25.0], 	
  [ 5,   6,  7,	2,	180.0,	25.0], 	
  [ 6,   7,  8,	2,	180.0,	25.0], 	
  [ 4,   9, 10,	2,	180.0,	25.0], 	
  [ 9,  10, 11,	2,	180.0,	25.0], 	
  [10,  11, 12,	2,	180.0,	25.0], 
]

[W]
atomnum = 1
atoms = [
# id 	type 	resnr 	residu 	atom 	cgnr 	charge
  [1, "W", 1, "W", "W", 1, 0], 
]
