name: build

on:
  push:
    branches: [ master, bonds-dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        sudo apt-get install libhdf5-openmpi-dev libfftw3-3 libfftw3-dev
        python -m pip install --upgrade pip
        pip install wheel
        pip install --upgrade numpy mpi4py cython
        pip install git+https://github.com/rainwoodman/pmesh
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest -v
