name: build

on:
  push:
    branches: [ master, parser ]
  pull_request:
    branches: [ master, parser ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        sudo apt-get install libhdf5-openmpi-dev libfftw3-3 libfftw3-dev
        python -m pip install --upgrade pip
        pip install wheel
        pip install pytest pytest-cov pytest-mpi coverage
        pip install --upgrade numpy mpi4py cython
        pip install -r requirements.txt
    - name: Compile fortran modules
      run: |
        cd hymd/
        make clean
        make
        cd ..
    - name: Test with pytest
      run: |
        NPROCS=6
        pytest -v --cov=./ --cov-report=
        mpirun -n ${NPROCS} utils/mute_all_ranks_except.sh 0 pytest -v --only-mpi --cov=./ --cov-append --cov-report=
        chmod +x pytest-mpi
        ./pytest-mpi --nprocs ${NPROCS} --order-output --verbose
    - name: Coverage report
      run: |
        coverage report
