name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-mpi4py python3-numpy
        sudo apt-get install -y libhdf5-openmpi-dev libfftw3-3 libfftw3-dev
    - name: Install python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade wheel numpy mpi4py cython
        python3 -m pip install -r requirements.txt
    - name: Install package
      run: |
        python3 -m pip install .
    - name: Test with pytest
      run: |
        python3 -m pip install pytest pytest-cov pytest-mpi coverage
        pytest --cov=./
        chmod +x pytest-mpi
        ./pytest-mpi -c -ca -n 2 -ns -oo
    - name: Coverage report and upload
      run: |
        coverage report
        coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
