name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/docs/buildDocs.sh') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Cache PLUMED
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ccache-reset1-linux-hash-${{ github.sha }}
        restore-keys: ccache-reset1-linux-hash-
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ccache
        sudo apt-get install -y python3-mpi4py python3-numpy
        sudo apt-get install -y libhdf5-openmpi-dev libfftw3-3 libfftw3-dev
    - name: Install PLUMED
      run: |
        mkdir -p $HOME/opt/
        sudo apt-get install -y build-essential
        sudo apt-get install -y openmpi-bin libopenmpi-dev git
        git clone https://github.com/plumed/plumed2.git
        cd plumed2
        echo "CC=mpicc" >> $GITHUB_ENV
        echo "CXX=mpic++" >> $GITHUB_ENV
        ccache -s -M 100M
        ./configure CXX="ccache $CXX" --disable-dependency-tracking --prefix=$HOME/opt
        make -j 4
        make install
        ccache -s -M 100M
        cd ../
    - name: Install python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade wheel numpy mpi4py cython
        python3 -m pip install -r requirements.txt
    - name: Install PLUMED python wrapper
      run: |
        cd plumed2/python
        make pip
        python3 -m pip install .
        cd ../../
        PLUMED_KERNEL=$HOME/opt/lib/libplumedKernel.so
    - name: Install package
      run: |
        python3 -m pip install .
    - name: Test with pytest
      run: |
        python3 -m pip install pytest pytest-cov pytest-mpi coverage
        pytest --cov=hymd --ignore=plumed2
        chmod +x pytest-mpi
        ./pytest-mpi -c -ca -n 2 -ns -oo
    - name: Coverage report and upload
      run: |
        coverage report
        coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
