name: docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_docs_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
    - name: Install build requirements
      shell: bash
      run: |
        apt-get update
        apt-get install -y git

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build docs and update gh-pages
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ls -lha
        docs/buildDocs.sh
