name: docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_docs_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/docs/buildDocs.sh') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-mpi4py python3-numpy
        sudo apt-get install -y libhdf5-openmpi-dev
    - name: Install python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade wheel numpy mpi4py cython
        python3 -m pip install -r requirements.txt
        python3 -m pip install jinja<3.1
    - name: Install package
      run: |
        python3 -m pip install .
    - name: Build docs
      shell: bash
      run: |
        docs/buildDocs.sh
    - name: Publish docs to gh-pages
      if: github.event_name == 'push'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docs/publishDocs.sh
